export {
  SnakeSimulator,
  applyDirection,
  canUseDirection,
  createDeterministicRandom,
  createDeterministicRandomFactory,
  createGameState,
  createSeededRandom,
  createSeededRandomFactory,
  createSimulatorSnapshot,
  createTestState,
  getRespawnCountdown,
  getRespawnRemainingMs,
  pickFoodCell,
  restartGame,
  runReplay,
  runReplayFrames,
  startCountdown,
  tick,
  togglePause,
} from './simulator';
export type {
  CreateStateOverrides,
  RandomSource,
  RandomSourceFactory,
  ReplayFrame,
  ReplayAction,
  ReplayScript,
  SimulatorAdvanceResult,
  SimulatorOptions,
  SimulatorPlayerSnapshot,
  SimulatorSnapshot,
} from './simulator';
export { chooseHeuristicDirection } from './bot';
